### ISSUE TITLE
Publishing only 1 time

### ISSUE THREAD

**Issue by sachanacar** [bennthomsen/CC3200_IBMIoT#1]
It seems that the code allows the TI sensor to publish only one set of data to IoT Foundation:

Publishing: 0{"d":{"myName":"TILaunchPad","temperature":20.80,"ambient":25.66,"X":0,"Y":-7,"Z":64,"RSSI":47}}

there is nothing that follows after that (eg. Publishing: 1, Publishing: 2....)

**Comment by bennthomsen** [comment]
If you select Tools>Board>Launchpad w/ cc3200 EMT (80MHz) and compile/upload then you will get the behaviour that you observed. If however you select Tools>Board>Launchpad w/ cc3200 (80MHz) then the code will work as expected and publish readings every 2 seconds. As to the solution for the EMT (aka. TI-RTOS) issue that will require more investigation and work.

**Comment by sachanacar** [comment]
@bennthomsen awesome that worked, thanks!
